### ISSUE TITLE
Add Recurring Services to the Out of Catchment Form

### ISSUE THREAD

**Issue by AnnieMungai** [OpenSRP/opensrp-client-path-zeir#10]
- [x] Update out of catchment area form with recurring services- see screenshot below). 
Note! Out of catchment form with recurring services is [here](https://docs.google.com/spreadsheets/d/1G8Fy7rxpqZ4v1Q7kgYEnffmkv8fvnsPe9vkUF6T53lg/edit#gid=1173845481) (check the "Out of Area Service" sheet- rows colored in light yellow - row 38 -40. 
![image](https://user-images.githubusercontent.com/58034047/106085534-6d4d3400-6131-11eb-865c-40affd97903d.png)

- [ ] The recurring services to sync like the out of catchment area vaccines.

**Comment by cafootitt** [comment]
@AnnieMungai There should be a data dictionary for the out of catchment area form. Please modify that by slotting in the recurring service questions, highlight the additions in a different color, and I can review.

**Comment by cafootitt** [comment]
For Vit A and deworming, we should ask which dose was given.

**Comment by rowo** [comment]
@AnnieMungai I was just [sketching out the recurring services](https://docs.google.com/forms/d/1iolNXmLOdO5WJ-yKqwP-psoRHqQGJTdgPxKmog1o2Ys/edit) part of this form to avoid the long lists of stuff (by first asking if any of the recurring services were provided and if so, then showing the name list and the date given.

But looking through the [dictionary](https://docs.google.com/spreadsheets/d/1E242clL01rA41b1nB0U763BCxiPFYbakzCmYdbyGYwg/edit#gid=2126764740), these dose number might not make sense as part of the out of area form (if these aren't as standardized as the vaccines since they are recurring). They depend on DOB and then after that the dates of the previous service. But since this is standalone, the date of previous would be unknown. Would it be better to put rough average ages for each dose name instead of just 1, 2, 3, 4...?

**Comment by AnnieMungai** [comment]
@rowo I think this is something that requires further discussion.

**Comment by cafootitt** [comment]
@rowo I think I can jump in here. 

We'll probably need to discuss the importance of the dose number. Keeping in mind that the event submitted here should go and record that service as complete in the server, and the services are by dose number, i.e. dose 2 can't be given before dose 1 is given. So if they're not marking the dose number in the form, does that really complicate things for us, as we'd have to look up the next service due for that service type and mark that as given.

I was thinking the dose number wouldn't be difficult to record, as I think that's how they record the doses in the child health card. They probably also know the expected dose number based on the child's age alone. Of course, this brings up the scenario whereby they record the wrong dose number that doesn't match the service that's currently due for that child, so in either case, we have to probably discuss with the engineering team how this event gets parsed into the service updates in the server.

No, they would never select more than one dose of a recurring service in the form (e.g. two Vitamin A doses would never be given at the same time).

**Comment by rowo** [comment]
@cafootitt 
1. I think what you are describing here kind of implies the response would be discarded if it's the wrong dose number (since if there's no logic to match it up when there's no dose marked, you probably wouldn't have it for when a specific dose is marked). So that's something to consider as the other side of that discussion.
2. That'd be great if they memorize the expected vaccine dose, Vit A, deworming, ITN based on a child's DOB or age. This was more of a just in case why not show the expected age for each dose option? 
3. Ok, so select ones, got it.

**Comment by AnnieMungai** [comment]
@rowo I have also worked out the data dictionary [here](https://docs.google.com/spreadsheets/d/1G8Fy7rxpqZ4v1Q7kgYEnffmkv8fvnsPe9vkUF6T53lg/edit#gid=1173845481). We can have more discussions around this.

**Comment by cafootitt** [comment]
@AnnieMungai We can discuss this with Elly on the standup tomorrow, so we can understand better how this event is stored.

**Comment by AnnieMungai** [comment]
@cafootitt I had a chat with @ellykits and @ndegwamartin on this, either way, it will be saved like an out of catchment recurring service event. This will update the child's record in one of 2 ways: 
1) Update the record with the next recurring service that was due - this allows us to just have a checkbox for each recurring service. 
2) Update the child record with the reccuring service that was given - so if a HW selects for example Vit A 4, this is what will be on the child's record. This will ignore any missed doses before this. 

I would suggest we go with option 1.

**Comment by AnnieMungai** [comment]
@cafootitt the recurring issue was resolved - I have updated on the original issue to include the data dictionary amended.

**Comment by cafootitt** [comment]
@AnnieMungai Is there an updated mockup for this? I don't know if Roger worked on one or provided one? If not, can you include a screenshot of the existing form to show how the vaccines are currently selected in the form?

I'm still not clear on how the recurring services will be saved to the child's record. If we go with Option 1: "Update the record with the next recurring service that was due - this allows us to just have a checkbox for each recurring service." - what does this mean? What if there is no recurring service due? Can you write up the steps of what should happen in a test case?

**Comment by AnnieMungai** [comment]
@cafootitt I am not sure we need a mock-up, a screenshot perhaps. @ellykits can explain how this will work (which is quite similar to the vaccines administered out of catchment). I believe the same logic works like when you input the wrong child vaccine.

**Comment by cafootitt** [comment]
@AnnieMungai Thanks for sharing the implementation document from Elly. There are two concerns/unanswered questions from the document: 

>> Referral Service schedules are not currently synced to the server so there is no way to know the clients next service date
How should we save the referral service schedule on the server

Have these been resolved? If so, are there implementation issues created to address them?

Finally, based on this workflow, can you write 2-3 test cases for QA in this issue?

**Comment by ellykits** [comment]
Hi @cafootitt . I scheduled a meeting with @ndegwamartin and @tychus6 tomorrow to try and find a solution to the 2 areas of concerns. So the two have not been resolved yet.

**Comment by ellykits** [comment]
@AnnieMungai @cafootitt From our discussion. We have resolved, syncing the schedule is not necessary as we can determine the right sequence number from the previously administered recurring service. Based on that decision on the form this is the only information the will be shown:
![recuring](https://user-images.githubusercontent.com/26865532/106249475-74ed0580-6223-11eb-8ca8-cd2901836fb8.png)

Then on the server side we determine the correct sequence based on the previous Recurring Service event.

**Comment by cafootitt** [comment]
@ellykits sounds good, thanks for documenting that here.

**Comment by AnnieMungai** [comment]
v.0.0.3
Looks good!
